name: Deploy Terraform in GCP

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2.1.8'
        with:
          create_credentials_file: 'true'
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth list
          gcloud compute zones describe europe-west3-a --project=${{ secrets.PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Use latest stable version

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Apply only on the main branch
        run: terraform apply -auto-approve tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
